version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:7.10
    
    working_directory: ~/repo

    environment:
      BRANCH: master
      BRANCH_DEV: dev
    
    steps:
      - checkout # check out the code in the project directory

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install new dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Cache new dependencies (if any) for future use
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run lint for syntax errors
      - run:
          name: Lint
          command: npm run lint

      # Build the VueJS cli project
      - run:
          name: Build
          command: |
            if [ "${CIRCLE_BRANCH}" == "${BRANCH_DEV}" ]; then
              npm run build
            fi          

      # Deploy to GitHub pages
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "${BRANCH_DEV}" ]; then
              bash .circleci/deploy.sh
            fi